// packages/react/src/useCountdown.ts
import { useState, useEffect, useRef } from 'react';

export function useCountdown(initialSeconds: number) {
  const [count, setCount] = useState(initialSeconds);
  const intervalRef = useRef<any>(null);

  const start = () => {
    if (intervalRef.current) clearInterval(intervalRef.current);
    intervalRef.current = setInterval(() => {
      setCount((prev) => {
        if (prev <= 0) {
          clearInterval(intervalRef.current);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
  };

  const stop = () => {
    if (intervalRef.current) clearInterval(intervalRef.current);
  };

  const reset = () => {
    stop();
    setCount(initialSeconds);
  };

  useEffect(() => {
    start();
    return stop;
  }, [initialSeconds]);

  return { count, start, stop, reset };
}

// packages/angular/src/useCountdown.ts
import { signal, Injector, inject, DestroyRef } from '@angular/core';

export function useCountdown(initialSeconds: number, injector?: Injector) {
  const count = signal(initialSeconds);
  let intervalId: any = null;
  const destroyRef = injector ? injector.get(DestroyRef) : inject(DestroyRef);

  const stop = () => {
    if (intervalId) clearInterval(intervalId);
  };

  const start = () => {
    stop();
    intervalId = setInterval(() => {
      if (count() <= 0) {
        stop();
        count.set(0);
      } else {
        count.update(v => v - 1);
      }
    }, 1000);
  };

  const reset = () => {
    stop();
    count.set(initialSeconds);
  };

  start();
  
  destroyRef.onDestroy(stop);

  return { count, start, stop, reset };
}
