// packages/react/src/useDocumentTitle.ts
import { useEffect, useRef } from 'react';
import { isBrowser } from '@shak-hooks/core';

export interface UseDocumentTitleOptions {
  restoreOnUnmount?: boolean;
}

export function useDocumentTitle(title: string, options: UseDocumentTitleOptions = {}) {
  const { restoreOnUnmount = false } = options;
  const defaultTitle = useRef(isBrowser ? document.title : '');

  useEffect(() => {
    if (!isBrowser) return;
    document.title = title;
  }, [title]);

  useEffect(() => {
    if (!isBrowser || !restoreOnUnmount) return;
    return () => {
      document.title = defaultTitle.current;
    };
  }, [restoreOnUnmount]);
}

// packages/angular/src/useDocumentTitle.ts
import { effect, inject, DestroyRef, Signal } from '@angular/core';
import { isBrowser } from '@shak-hooks/core';

export interface UseDocumentTitleOptions {
  restoreOnUnmount?: boolean;
}

export function useDocumentTitle(title: Signal<string> | string, options: UseDocumentTitleOptions = {}) {
  const { restoreOnUnmount = false } = options;
  const defaultTitle = isBrowser ? document.title : '';

  if (isBrowser) {
    if (typeof title === 'string') {
      document.title = title;
    } else {
      effect(() => {
        document.title = title();
      });
    }

    try {
      const destroyRef = inject(DestroyRef);
      destroyRef.onDestroy(() => {
        if (restoreOnUnmount) {
          document.title = defaultTitle;
        }
      });
    } catch (e) {}
  }
}
