// packages/react/src/useEventListener.ts
import { useEffect, useRef } from 'react';
import { isBrowser } from '@shak-hooks/core';

export function useEventListener(
  eventName: string,
  handler: (event: any) => void,
  element?: EventTarget | null
) {
  const savedHandler = useRef(handler);

  useEffect(() => {
    savedHandler.current = handler;
  }, [handler]);

  useEffect(() => {
    const targetElement: EventTarget | Window = element || (isBrowser ? window : null) as any;
    if (!isBrowser || !targetElement) return;

    const eventListener = (event: Event) => savedHandler.current(event);

    targetElement.addEventListener(eventName, eventListener);

    return () => {
      targetElement.removeEventListener(eventName, eventListener);
    };
  }, [eventName, element]);
}

// packages/angular/src/useEventListener.ts
import { effect, inject, DestroyRef, ElementRef, Signal } from '@angular/core';
import { isBrowser } from '@shak-hooks/core';

export function useEventListener(
  target: EventTarget | Signal<EventTarget | null> | ElementRef | string,
  eventNameOrHandler: string | ((event: any) => void),
  handler?: (event: any) => void
) {
  if (!isBrowser) return;

  let eventName: string;
  let listener: (event: any) => void;
  let targetSource: any = target;

  if (typeof target === 'string') {
    eventName = target;
    listener = eventNameOrHandler as any;
    targetSource = window;
  } else {
    eventName = eventNameOrHandler as string;
    listener = handler!;
  }

  let cleanup = () => {};

  const register = (el: EventTarget | null) => {
    cleanup();
    if (!el) return;
    el.addEventListener(eventName, listener);
    cleanup = () => el.removeEventListener(eventName, listener);
  };

  if (typeof targetSource === 'function') {
     effect(() => {
         register(targetSource());
     });
  } else if (targetSource instanceof ElementRef) {
      register(targetSource.nativeElement);
  } else {
      register(targetSource);
  }

  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(cleanup);
  } catch (e) {}
}
