// packages/react/src/useHover.ts
import { useState, RefObject } from 'react';
import { useEventListener } from './useEventListener';

export function useHover<T extends HTMLElement = HTMLElement>(
  elementRef: RefObject<T>
): boolean {
  const [value, setValue] = useState<boolean>(false);

  const handleMouseEnter = () => setValue(true);
  const handleMouseLeave = () => setValue(false);

  useEventListener('mouseenter', handleMouseEnter, elementRef.current);
  useEventListener('mouseleave', handleMouseLeave, elementRef.current);

  return value;
}

// packages/angular/src/useHover.ts
import { signal, ElementRef, Signal } from '@angular/core';
import { useEventListener } from './useEventListener';

export function useHover(target: ElementRef | Signal<HTMLElement | null> | HTMLElement) {
  const isHovered = signal(false);

  useEventListener(target, 'mouseenter', () => {
    isHovered.set(true);
  });

  useEventListener(target, 'mouseleave', () => {
    isHovered.set(false);
  });

  return isHovered;
}
