// packages/react/src/useKeyPress.ts
import { useState, useEffect } from 'react';

export function useKeyPress(targetKey: string) {
  const [keyPressed, setKeyPressed] = useState(false);

  useEffect(() => {
    const downHandler = ({ key }: KeyboardEvent) => {
      if (key === targetKey) {
        setKeyPressed(true);
      }
    };

    const upHandler = ({ key }: KeyboardEvent) => {
      if (key === targetKey) {
        setKeyPressed(false);
      }
    };

    window.addEventListener('keydown', downHandler);
    window.addEventListener('keyup', upHandler);

    return () => {
      window.removeEventListener('keydown', downHandler);
      window.removeEventListener('keyup', upHandler);
    };
  }, [targetKey]);

  return keyPressed;
}

// packages/angular/src/useKeyPress.ts
import { signal, Injector, inject, DestroyRef } from '@angular/core';

export function useKeyPress(targetKey: string, injector?: Injector) {
  const keyPressed = signal(false);
  const destroyRef = injector ? injector.get(DestroyRef) : inject(DestroyRef);

  const downHandler = ({ key }: KeyboardEvent) => {
    if (key === targetKey) {
      keyPressed.set(true);
    }
  };

  const upHandler = ({ key }: KeyboardEvent) => {
    if (key === targetKey) {
      keyPressed.set(false);
    }
  };

  window.addEventListener('keydown', downHandler);
  window.addEventListener('keyup', upHandler);

  destroyRef.onDestroy(() => {
    window.removeEventListener('keydown', downHandler);
    window.removeEventListener('keyup', upHandler);
  });

  return keyPressed;
}
