// packages/react/src/useMap.ts
import { useState, useMemo } from 'react';

export function useMap<K, V>(initialValue?: Iterable<readonly [K, V]>) {
  const [map, setMap] = useState(new Map<K, V>(initialValue));

  const actions = useMemo(
    () => ({
      set: (key: K, value: V) => {
        setMap((prev) => {
          const next = new Map(prev);
          next.set(key, value);
          return next;
        });
      },
      remove: (key: K) => {
        setMap((prev) => {
          const next = new Map(prev);
          next.delete(key);
          return next;
        });
      },
      clear: () => {
        setMap(new Map());
      },
      reset: () => {
        setMap(new Map(initialValue));
      },
    }),
    [initialValue]
  );

  return [map, actions] as const;
}

// packages/angular/src/useMap.ts
import { signal } from '@angular/core';

export function useMap<K, V>(initialValue?: Iterable<readonly [K, V]>) {
  const map = signal(new Map<K, V>(initialValue));

  const set = (key: K, value: V) => {
    map.update(prev => {
      const next = new Map(prev);
      next.set(key, value);
      return next;
    });
  };

  const remove = (key: K) => {
    map.update(prev => {
      const next = new Map(prev);
      next.delete(key);
      return next;
    });
  };

  const clear = () => {
    map.set(new Map());
  };

  const reset = () => {
    map.set(new Map(initialValue));
  };

  return {
    map,
    set,
    remove,
    clear,
    reset,
  };
}
