// packages/react/src/useOrientation.ts
import { useState, useEffect } from 'react';
import { isBrowser } from '@shak-hooks/core';

export interface OrientationState {
  angle: number;
  type: string;
}

const defaultState: OrientationState = {
  angle: 0,
  type: 'landscape-primary',
};

export function useOrientation(): OrientationState {
  const [state, setState] = useState(defaultState);

  useEffect(() => {
    if (!isBrowser) return;

    const handleChange = () => {
      const { angle, type } = window.screen.orientation;
      setState({ angle, type });
    };

    const handleOrientationChange = () => {
        // Fallback for older browsers
        setState({
            angle: Number(window.orientation) || 0,
            type: 'unknown'
        });
    }

    if (window.screen?.orientation) {
        handleChange();
        window.screen.orientation.addEventListener('change', handleChange);
    } else {
        window.addEventListener('orientationchange', handleOrientationChange);
    }

    return () => {
      if (window.screen?.orientation) {
        window.screen.orientation.removeEventListener('change', handleChange);
      } else {
        window.removeEventListener('orientationchange', handleOrientationChange);
      }
    };
  }, []);

  return state;
}

// packages/angular/src/useOrientation.ts
import { signal, inject, DestroyRef } from '@angular/core';
import { isBrowser } from '@shak-hooks/core';

export function useOrientation() {
  const angle = signal(0);
  const type = signal('landscape-primary');

  if (isBrowser) {
    const updateState = () => {
        if (window.screen?.orientation) {
            angle.set(window.screen.orientation.angle);
            type.set(window.screen.orientation.type);
        } else if (typeof window.orientation !== 'undefined') {
            angle.set(Number(window.orientation));
            type.set('unknown');
        }
    };

    updateState();

    if (window.screen?.orientation) {
        window.screen.orientation.addEventListener('change', updateState);
    } else {
        window.addEventListener('orientationchange', updateState);
    }

    try {
      const destroyRef = inject(DestroyRef);
      destroyRef.onDestroy(() => {
        if (window.screen?.orientation) {
            window.screen.orientation.removeEventListener('change', updateState);
        } else {
            window.removeEventListener('orientationchange', updateState);
        }
      });
    } catch (e) {}
  }

  return { angle, type };
}
