// packages/react/src/useRandomInterval.ts
import { useRef, useEffect, useCallback } from 'react';

const random = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min)) + min;

export function useRandomInterval(
  callback: () => void,
  minDelay: number | null,
  maxDelay: number | null
) {
  const timeoutId = useRef<number | null>(null);
  const savedCallback = useRef(callback);

  useEffect(() => {
    savedCallback.current = callback;
  }, [callback]);

  useEffect(() => {
    const isEnabled =
      typeof minDelay === 'number' && typeof maxDelay === 'number';
    if (isEnabled) {
      const handleTick = () => {
        const nextTickAt = random(minDelay, maxDelay);
        timeoutId.current = window.setTimeout(() => {
          savedCallback.current();
          handleTick();
        }, nextTickAt);
      };
      handleTick();
    }
    return () => {
      if (timeoutId.current) {
        window.clearTimeout(timeoutId.current);
      }
    };
  }, [minDelay, maxDelay]);

  const cancel = useCallback(() => {
    if (timeoutId.current) {
      window.clearTimeout(timeoutId.current);
    }
  }, []);

  return cancel;
}

// packages/angular/src/useRandomInterval.ts
import { effect, inject, DestroyRef, Signal } from '@angular/core';

const random = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min)) + min;

export function useRandomInterval(
  callback: () => void,
  minDelay: Signal<number | null> | number | null,
  maxDelay: Signal<number | null> | number | null
) {
  let timeoutId: number | null = null;

  const clean = () => {
    if (timeoutId) {
      window.clearTimeout(timeoutId);
      timeoutId = null;
    }
  };

  const start = () => {
    clean();
    const min = typeof minDelay === 'function' ? minDelay() : minDelay;
    const max = typeof maxDelay === 'function' ? maxDelay() : maxDelay;

    if (typeof min === 'number' && typeof max === 'number') {
      const handleTick = () => {
        const nextTickAt = random(min, max);
        timeoutId = window.setTimeout(() => {
          callback();
          handleTick();
        }, nextTickAt);
      };
      handleTick();
    }
  };

  if (typeof minDelay === 'function' || typeof maxDelay === 'function') {
      effect(() => {
          if (typeof minDelay === 'function') minDelay();
          if (typeof maxDelay === 'function') maxDelay();
          start();
      });
  } else {
      start();
  }

  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(clean);
  } catch (e) {}

  return clean;
}
