// packages/react/src/useRenderInfo.ts
import { useRef, useEffect } from 'react';

export function useRenderInfo(name: string = 'Component') {
  const count = useRef(0);
  const lastRender = useRef(Date.now());

  useEffect(() => {
    const now = Date.now();
    count.current++;
    console.log(`${name} rendered`, {
      count: count.current,
      sinceLast: now - lastRender.current,
      timestamp: now,
    });
    lastRender.current = now;
  });
}

// packages/angular/src/useRenderInfo.ts
import { afterRender, Injector } from "@angular/core";

export function useRenderInfo(name: string = "Component", injector?: Injector) {
  let count = 0;
  let lastRender = Date.now();

  afterRender(() => {
    const now = Date.now();
    count++;
    console.log(`${name} rendered`, {
      count,
      sinceLast: now - lastRender,
      timestamp: now,
    });
    lastRender = now;
  }, { injector });
}
