// packages/react/src/useToggle.ts
import { useState, useCallback } from 'react';

export function useToggle(initialValue: boolean = false) {
  const [value, setValue] = useState(initialValue);
  const toggle = useCallback((nextValue?: any) => {
    if (typeof nextValue === 'boolean') {
      setValue(nextValue);
    } else {
      setValue((v) => !v);
    }
  }, []);
  return [value, toggle] as const;
}

// packages/angular/src/useToggle.ts
import { signal } from '@angular/core';

export function useToggle(initialValue: boolean = false) {
  const value = signal(initialValue);
  const toggle = (nextValue?: any) => {
    if (typeof nextValue === 'boolean') {
      value.set(nextValue);
    } else {
      value.update(v => !v);
    }
  };
  return { value, toggle };
}
