// packages/react/src/useWindowSize.ts
import { useState, useEffect } from 'react';
import { isBrowser } from '@shak-hooks/core';

export interface WindowSize {
  width: number;
  height: number;
}

export function useWindowSize(): WindowSize {
  const [windowSize, setWindowSize] = useState<WindowSize>({
    width: isBrowser ? window.innerWidth : 0,
    height: isBrowser ? window.innerHeight : 0,
  });

  useEffect(() => {
    if (!isBrowser) return;

    const handleResize = () => {
      setWindowSize({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return windowSize;
}

// packages/angular/src/useWindowSize.ts
import { signal, inject, DestroyRef } from '@angular/core';
import { isBrowser } from '@shak-hooks/core';

export interface WindowSize {
  width: number;
  height: number;
}

export function useWindowSize() {
  const width = signal(isBrowser ? window.innerWidth : 0);
  const height = signal(isBrowser ? window.innerHeight : 0);

  if (isBrowser) {
    const handleResize = () => {
      width.set(window.innerWidth);
      height.set(window.innerHeight);
    };

    window.addEventListener('resize', handleResize);
    
    try {
      const destroyRef = inject(DestroyRef);
      destroyRef.onDestroy(() => {
        window.removeEventListener('resize', handleResize);
      });
    } catch (e) {
      console.warn('useWindowSize: Could not inject DestroyRef. Event listener will not be cleaned up automatically.');
    }
  }

  return { width, height };
}
