// packages/angular/src/useClickAway.ts
import { ElementRef, Signal } from '@angular/core';
import { useEventListener } from './useEventListener';

export function useClickAway(
  target: ElementRef | Signal<HTMLElement | null> | HTMLElement,
  handler: (event: Event) => void,
  events: string[] = ['mousedown', 'touchstart']
) {
  const listener = (event: Event) => {
    let el: HTMLElement | null = null;
    
    if (target instanceof ElementRef) {
        el = target.nativeElement;
    } else if (typeof target === 'function') {
        el = target();
    } else {
        el = target;
    }

    if (!el) return;

    if (el === event.target || event.composedPath().includes(el)) {
      return;
    }

    handler(event);
  };

  events.forEach((event) => {
    useEventListener(event, listener);
  });
}

// packages/react/src/useClickAway.ts
import { RefObject, useEffect, useRef } from 'react';
import { useEventListener } from './useEventListener';

export function useClickAway<T extends Event = Event>(
  ref: RefObject<HTMLElement | null>,
  handler: (event: T) => void,
  events: string[] = ['mousedown', 'touchstart']
) {
  const savedHandler = useRef(handler);

  useEffect(() => {
    savedHandler.current = handler;
  }, [handler]);

  useEffect(() => {
    const listener = (event: any) => {
      const el = ref.current;
      if (!el || el.contains(event.target as Node)) {
        return;
      }
      savedHandler.current(event);
    };

    for (const eventName of events) {
      document.addEventListener(eventName, listener);
    }

    return () => {
      for (const eventName of events) {
        document.removeEventListener(eventName, listener);
      }
    };
  }, [ref, events]);
}
