// packages/angular/src/useFetch.ts
import { signal, effect, inject, DestroyRef, Signal } from '@angular/core';

export interface UseFetchOptions extends RequestInit {
  immediate?: boolean;
}

export function useFetch<T = any>(
  url: Signal<string> | string,
  options: UseFetchOptions = {}
) {
  const { immediate = true, ...fetchOptions } = options;
  const data = signal<T | null>(null);
  const error = signal<Error | null>(null);
  const loading = signal<boolean>(false);
  
  let abortController: AbortController | null = null;

  const abort = () => {
    if (abortController) {
      abortController.abort();
      abortController = null;
    }
  };

  const execute = async () => {
    const currentUrl = typeof url === 'string' ? url : url();
    
    loading.set(true);
    error.set(null);
    data.set(null);

    abort();

    const controller = new AbortController();
    abortController = controller;

    try {
      const response = await fetch(currentUrl, {
        ...fetchOptions,
        signal: controller.signal,
      });

      if (!response.ok) {
        throw new Error(response.statusText);
      }

      const json = await response.json();
      data.set(json);
    } catch (err: any) {
      if (err.name !== 'AbortError') {
        error.set(err);
      }
    } finally {
      if (abortController === controller) {
        loading.set(false);
      }
    }
  };

  if (immediate) {
    if (typeof url === 'function') {
        effect(() => {
            // Track url dependency
            url();
            execute();
        }, { allowSignalWrites: true });
    } else {
        execute();
    }
  }

  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(() => {
      abort();
    });
  } catch (e) {}

  return { data, error, loading, execute, abort };
}

// packages/react/src/useFetch.ts
import { useState, useEffect, useCallback, useRef } from 'react';

export interface UseFetchOptions extends RequestInit {
  immediate?: boolean;
}

export interface UseFetchReturn<T> {
  data: T | null;
  error: Error | null;
  loading: boolean;
  execute: () => Promise<void>;
  abort: () => void;
}

export function useFetch<T = any>(
  url: string,
  options: UseFetchOptions = {}
): UseFetchReturn<T> {
  const { immediate = true, ...fetchOptions } = options;
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  
  const abortControllerRef = useRef<AbortController | null>(null);

  const execute = useCallback(async () => {
    setLoading(true);
    setError(null);
    setData(null);

    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }

    const controller = new AbortController();
    abortControllerRef.current = controller;

    try {
      const response = await fetch(url, {
        ...fetchOptions,
        signal: controller.signal,
      });

      if (!response.ok) {
        throw new Error(response.statusText);
      }

      const json = await response.json();
      setData(json);
    } catch (err: any) {
      if (err.name !== 'AbortError') {
        setError(err);
      }
    } finally {
      if (abortControllerRef.current === controller) {
        setLoading(false);
      }
    }
  }, [url, JSON.stringify(fetchOptions)]);

  const abort = useCallback(() => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
  }, []);

  useEffect(() => {
    if (immediate) {
      execute();
    }
    return () => {
      abort();
    };
  }, [execute, immediate, abort]);

  return { data, error, loading, execute, abort };
}
