// packages/angular/src/useGeolocation.ts
import { signal, Injector, inject, DestroyRef } from '@angular/core';

export function useGeolocation(options?: PositionOptions, injector?: Injector) {
  const loading = signal(true);
  const accuracy = signal<number | null>(null);
  const altitude = signal<number | null>(null);
  const altitudeAccuracy = signal<number | null>(null);
  const heading = signal<number | null>(null);
  const latitude = signal<number | null>(null);
  const longitude = signal<number | null>(null);
  const speed = signal<number | null>(null);
  const timestamp = signal<number | null>(null);
  const error = signal<GeolocationPositionError | null>(null);
  
  const destroyRef = injector ? injector.get(DestroyRef) : inject(DestroyRef);

  let watchId: number;

  const onEvent = ({ coords, timestamp: ts }: GeolocationPosition) => {
    loading.set(false);
    timestamp.set(ts);
    latitude.set(coords.latitude);
    longitude.set(coords.longitude);
    altitude.set(coords.altitude);
    accuracy.set(coords.accuracy);
    altitudeAccuracy.set(coords.altitudeAccuracy);
    heading.set(coords.heading);
    speed.set(coords.speed);
    error.set(null);
  };

  const onError = (err: GeolocationPositionError) => {
    loading.set(false);
    error.set(err);
  };

  navigator.geolocation.getCurrentPosition(onEvent, onError, options);
  watchId = navigator.geolocation.watchPosition(onEvent, onError, options);

  destroyRef.onDestroy(() => {
    navigator.geolocation.clearWatch(watchId);
  });

  return {
    loading,
    accuracy,
    altitude,
    altitudeAccuracy,
    heading,
    latitude,
    longitude,
    speed,
    timestamp,
    error,
  };
}

// packages/react/src/useGeolocation.ts
import { useState, useEffect } from 'react';

export function useGeolocation(options?: PositionOptions) {
  const [state, setState] = useState<{
    loading: boolean;
    accuracy: number | null;
    altitude: number | null;
    altitudeAccuracy: number | null;
    heading: number | null;
    latitude: number | null;
    longitude: number | null;
    speed: number | null;
    timestamp: number | null;
    error: GeolocationPositionError | null;
  }>({
    loading: true,
    accuracy: null,
    altitude: null,
    altitudeAccuracy: null,
    heading: null,
    latitude: null,
    longitude: null,
    speed: null,
    timestamp: null,
    error: null,
  });

  useEffect(() => {
    const onEvent = ({ coords, timestamp }: GeolocationPosition) => {
      setState({
        loading: false,
        timestamp,
        latitude: coords.latitude,
        longitude: coords.longitude,
        altitude: coords.altitude,
        accuracy: coords.accuracy,
        altitudeAccuracy: coords.altitudeAccuracy,
        heading: coords.heading,
        speed: coords.speed,
        error: null,
      });
    };

    const onError = (error: GeolocationPositionError) => {
      setState((s) => ({ ...s, loading: false, error }));
    };

    navigator.geolocation.getCurrentPosition(onEvent, onError, options);
    const watchId = navigator.geolocation.watchPosition(onEvent, onError, options);

    return () => navigator.geolocation.clearWatch(watchId);
  }, [options]);

  return state;
}
