// packages/angular/src/useHistoryState.ts
import { signal } from '@angular/core';

export function useHistoryState<T>(initialValue: T, key: string) {
  const state = signal<T>(initialValue);
  
  // Initialize
  const historyState = window.history.state;
  if (historyState && historyState[key] !== undefined) {
      state.set(historyState[key]);
  }

  const setHistoryState = (value: T) => {
    const newState = { ...window.history.state, [key]: value };
    window.history.replaceState(newState, '');
    state.set(value);
  };

  return { state, setHistoryState };
}

// packages/react/src/useHistoryState.ts
import { useState, useCallback } from 'react';

export function useHistoryState<T>(initialValue: T, key: string) {
  const [state, setState] = useState<T>(() => {
    const historyState = window.history.state;
    return historyState && historyState[key] !== undefined ? historyState[key] : initialValue;
  });

  const setHistoryState = useCallback((value: T) => {
    const newState = { ...window.history.state, [key]: value };
    window.history.replaceState(newState, '');
    setState(value);
  }, [key]);

  return [state, setHistoryState] as const;
}
