// packages/angular/src/useLockBodyScroll.ts
import { effect, Injector, inject, DestroyRef } from '@angular/core';

export function useLockBodyScroll(locked: (() => boolean) | boolean = true, injector?: Injector) {
  const destroyRef = injector ? injector.get(DestroyRef) : inject(DestroyRef);
  let originalStyle = '';

  // Initialize
  originalStyle = document.body.style.overflow;

  const isLocked = typeof locked === 'function' ? (locked as () => boolean) : () => locked as boolean;

  effect(() => {
    if (isLocked()) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = originalStyle;
    }
  }, { injector });

  destroyRef.onDestroy(() => {
    document.body.style.overflow = originalStyle;
  });
}

// packages/react/src/useLockBodyScroll.ts
import { useLayoutEffect } from 'react';

export function useLockBodyScroll(locked: boolean = true) {
  useLayoutEffect(() => {
    if (!locked) return;
    const originalStyle = window.getComputedStyle(document.body).overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = originalStyle;
    };
  }, [locked]);
}
