// packages/angular/src/useLongPress.ts
import { Injector, inject, DestroyRef } from '@angular/core';

export function useLongPress(
  callback: (e: any) => void,
  options: { threshold?: number; onStart?: (e: any) => void; onFinish?: (e: any) => void; onCancel?: (e: any) => void } = {},
  injector?: Injector
) {
  const { threshold = 400, onStart, onFinish, onCancel } = options;
  let timer: any = null;
  let isLongPress = false;
  
  const destroyRef = injector ? injector.get(DestroyRef) : inject(DestroyRef);

  const start = (event: any) => {
    if (onStart) onStart(event);
    isLongPress = false;
    timer = setTimeout(() => {
      isLongPress = true;
      callback(event);
    }, threshold);
  };

  const stop = (event: any) => {
    if (timer) {
      clearTimeout(timer);
      timer = null;
    }
    if (isLongPress) {
      if (onFinish) onFinish(event);
    } else {
      if (onCancel) onCancel(event);
    }
  };

  destroyRef.onDestroy(() => {
    if (timer) clearTimeout(timer);
  });

  return {
    onMouseDown: start,
    onMouseUp: stop,
    onMouseLeave: stop,
    onTouchStart: start,
    onTouchEnd: stop,
  };
}

// packages/react/src/useLongPress.ts
import { useCallback, useRef } from 'react';

export function useLongPress(
  callback: (e: any) => void,
  options: { threshold?: number; onStart?: (e: any) => void; onFinish?: (e: any) => void; onCancel?: (e: any) => void } = {}
) {
  const { threshold = 400, onStart, onFinish, onCancel } = options;
  const timerRef = useRef<any>(null);
  const isLongPress = useRef(false);

  const start = useCallback(
    (event: any) => {
      if (onStart) onStart(event);
      isLongPress.current = false;
      timerRef.current = setTimeout(() => {
        isLongPress.current = true;
        callback(event);
      }, threshold);
    },
    [callback, threshold, onStart]
  );

  const stop = useCallback(
    (event: any) => {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
        timerRef.current = null;
      }
      if (isLongPress.current) {
        if (onFinish) onFinish(event);
      } else {
        if (onCancel) onCancel(event);
      }
    },
    [onFinish, onCancel]
  );

  return {
    onMouseDown: start,
    onMouseUp: stop,
    onMouseLeave: stop,
    onTouchStart: start,
    onTouchEnd: stop,
  };
}
