// packages/angular/src/usePreferredLanguage.ts
import { signal, inject, DestroyRef } from '@angular/core';
import { isBrowser } from '@shak-hooks/core';

export function usePreferredLanguage() {
  const language = signal(isBrowser ? navigator.language : 'en');

  if (isBrowser) {
    const handleLanguageChange = () => {
      language.set(navigator.language);
    };

    window.addEventListener('languagechange', handleLanguageChange);

    try {
      const destroyRef = inject(DestroyRef);
      destroyRef.onDestroy(() => {
        window.removeEventListener('languagechange', handleLanguageChange);
      });
    } catch (e) {}
  }

  return language;
}

// packages/react/src/usePreferredLanguage.ts
import { useState, useEffect } from 'react';
import { isBrowser } from '@shak-hooks/core';

export function usePreferredLanguage(): string {
  const [language, setLanguage] = useState<string>(() => {
    if (isBrowser) {
      return navigator.language;
    }
    return 'en';
  });

  useEffect(() => {
    if (!isBrowser) return;

    const handleLanguageChange = () => {
      setLanguage(navigator.language);
    };

    window.addEventListener('languagechange', handleLanguageChange);
    return () => window.removeEventListener('languagechange', handleLanguageChange);
  }, []);

  return language;
}
