// packages/angular/src/useTimeout.ts
import { effect, inject, DestroyRef, Signal } from '@angular/core';

export function useTimeout(callback: () => void, delay: Signal<number | null> | number | null) {
  let id: any = null;

  const clean = () => {
    if (id) {
      clearTimeout(id);
      id = null;
    }
  };

  const start = () => {
    clean();
    const d = typeof delay === 'function' ? delay() : delay;
    if (d !== null) {
      id = setTimeout(callback, d);
    }
  };

  if (typeof delay === 'function') {
      effect(() => {
          delay();
          start();
      });
  } else {
      start();
  }

  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(clean);
  } catch (e) {}
}

// packages/react/src/useTimeout.ts
import { useEffect, useRef } from 'react';

export function useTimeout(callback: () => void, delay: number | null) {
  const savedCallback = useRef(callback);

  useEffect(() => {
    savedCallback.current = callback;
  }, [callback]);

  useEffect(() => {
    if (delay !== null) {
      const id = setTimeout(() => savedCallback.current(), delay);
      return () => clearTimeout(id);
    }
  }, [delay]);
}
